<?php
/**
 * Header
 *
 * Global site header. Starts a page wrap with <main> that is closed in footer.php
 *
 * @package Vitamin\Vanilla_Theme\Core_Components
 * @author  Vitamin
 * @version 1.0.0
 */

use Timber\Timber;
use Timber\Menu;
use Timber\Post;

?>

<!DOCTYPE html>
<html <?php language_attributes(); ?>>
	<head>
		<?php if ( 'production' === $_ENV['location'] ) : ?>
			<!-- Google Tag Manager -->
			<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
			new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
			j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
			'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
			})(window,document,'script','dataLayer','GTM-P275H5G');</script>
			<!-- End Google Tag Manager -->

			<!-- Google Optimize -->
			<!-- <script src="https://www.googleoptimize.com/optimize.js?id=OPT-KHJ3STZ"></script> -->
			<!-- End Google Optimize -->

			<!-- Hotjar Tracking Code for https://www.overleaonline.org/ -->
			<script>
				(function(h,o,t,j,a,r){
					h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
					h._hjSettings={hjid:3093691,hjsv:6};
					a=o.getElementsByTagName('head')[0];
					r=o.createElement('script');r.async=1;
					r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
					a.appendChild(r);
				})(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
			</script>
		<?php endif; ?>

		<meta charset="<?php bloginfo( 'charset' ); ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Replace with code generated by https://realfavicongenerator.net/ -->
		<link rel="apple-touch-icon" sizes="180x180" href="<?php echo esc_url( get_theme_file_uri( 'favicon/apple-touch-icon.png' ) ); ?>">
		<link rel="icon" type="image/png" sizes="32x32" href="<?php echo esc_url( get_theme_file_uri( 'favicon/favicon-32x32.png' ) ); ?>">
		<link rel="icon" type="image/png" sizes="16x16" href="<?php echo esc_url( get_theme_file_uri( 'favicon/favicon-16x16.png' ) ); ?>">
		<link rel="manifest" href="<?php echo esc_url( get_theme_file_uri( 'favicon/site.webmanifest' ) ); ?>">
		<link rel="mask-icon" href="<?php echo esc_url( get_theme_file_uri( 'favicon/safari-pinned-tab.svg' ) ); ?>" color="#003d3c">
		<link rel="shortcut icon" href="<?php echo esc_url( get_theme_file_uri( 'favicon/favicon.ico' ) ); ?>">
		<meta name="msapplication-TileColor" content="#003d3c">
		<meta name="msapplication-config" content="<?php echo esc_url( get_theme_file_uri( '' ) ); ?>/favicon/browserconfig.xml">
		<meta name="theme-color" content="#003d3c">
		<!-- End favicon -->

		<?php wp_head(); ?>
	</head>
	<?php
		$context         = Timber::context();
		$alert = ($context['options']['alert_show']) ? 'v-alert--true' : 'v-alert--false';
	?>
	<body <?php body_class( $alert ); ?>>
		<?php wp_body_open(); ?>

		<?php if ( 'production' === $_ENV['location'] ) : ?>
			<!-- Google Tag Manager (noscript) -->
			<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P275H5G"
			height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
			<!-- End Google Tag Manager (noscript) -->
		<?php endif; ?>

		<article class="v-unsupported-browser">
			<div class="container">
				<p class="v-unsupported-browser__text">
					The browser you are using is not supported. Please consider using a <a href="https://browsehappy.com/" class="v-unsupported-browser__link">modern browser</a>.
				</p>
			</div>
		</article>
		<script nomodule>
			/* Style banner before uncommenting */
			// document.querySelector('.v-unsupported-browser').style.display = 'block';
		</script>

		<a href="#v-content" class="v-skip-nav">Skip Navigation</a>

		<?php
			Timber::render( 'alert/alert.twig', $context);
		?>

		<?php
			$context['post'] = new Post();
			$context['menu'] = new Menu( 'header_nav' );
			Timber::render( 'header/header.twig', $context );
		?>

		<main class="v-main" id="v-content">
