<?php
/**
 * Header
 *
 * Global site header. Starts a page wrap with <main> that is closed in footer.php
 *
 * @package Vitamin\Vanilla_Theme\Core_Components
 * @author  Vitamin
 * @version 1.0.0
 */

use Timber\Timber;
use Timber\Menu;
use Timber\Post;

?>

<!DOCTYPE html>
<html <?php language_attributes(); ?>>
	<head>
		<?php if ( 'production' === $_ENV['location'] ) : ?>
			<!-- Paste GA/GTag code here -->
		<?php endif; ?>

		<meta charset="<?php bloginfo( 'charset' ); ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Replace with code generated by https://realfavicongenerator.net/ -->
		<link rel="apple-touch-icon" sizes="180x180" href="<?php echo esc_url( get_theme_file_uri( 'favicon/apple-touch-icon.png' ) ); ?>">
		<link rel="icon" type="image/png" sizes="32x32" href="<?php echo esc_url( get_theme_file_uri( 'favicon/favicon-32x32.png' ) ); ?>">
		<link rel="icon" type="image/png" sizes="16x16" href="<?php echo esc_url( get_theme_file_uri( 'favicon/favicon-16x16.png' ) ); ?>">
		<link rel="manifest" href="<?php echo esc_url( get_theme_file_uri( 'favicon/site.webmanifest' ) ); ?>">
		<link rel="mask-icon" href="<?php echo esc_url( get_theme_file_uri( 'favicon/safari-pinned-tab.svg' ) ); ?>" color="#1f79c1">
		<link rel="shortcut icon" href="<?php echo esc_url( get_theme_file_uri( 'favicon/favicon.ico' ) ); ?>">
		<meta name="msapplication-TileColor" content="#1f79c1">
		<meta name="msapplication-config" content="<?php echo esc_url( get_theme_file_uri( '' ) ); ?>/favicon/browserconfig.xml">
		<meta name="theme-color" content="#000000">
		<!-- End favicon -->

		<?php wp_head(); ?>
	</head>
	<body <?php body_class(); ?>>
		<?php wp_body_open(); ?>

		<?php if ( 'production' === $_ENV['location'] ) : ?>
			<!-- Paste GA/GTag code here -->
		<?php endif; ?>

		<article class="v-unsupported-browser">
			<div class="container">
				<p class="v-unsupported-browser__text">
					The browser you are using is not supported. Please consider using a <a href="https://browsehappy.com/" class="v-unsupported-browser__link">modern browser</a>.
				</p>
			</div>
		</article>
		<script nomodule>
			/* Style banner before uncommenting */
			// document.querySelector('.v-unsupported-browser').style.display = 'block';
		</script>

		<a href="#v-content" class="v-skip-nav">Skip Navigation</a>

		<?php
			$context         = Timber::context();
			$context['menu'] = new Menu( 'header_nav' );
			$context['post'] = new Post();
			Timber::render( 'header/header.twig', $context );
		?>

		<main class="v-main" id="v-content">
